
name = "DashDvx"
uuid = "1b08a953-4be3-4667-9a23-9a352cfe7e91"
authors = ["Geraldine Geoffroy <geraldine.geoffroy@univ-cotedazur.fr>"]
version = "1.3.1"

[deps]
Dash = "1b08a953-4be3-4667-9a23-3db579824955"

[compat]
julia = "1.2"
Dash = "0.1.3, 1.0"
